# -*- coding: utf-8 -*-
"""Atividade-Semana-04-Aline-Melo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2Zbr1pjK30V2bqJqN8-hC6JSz3EJvLv

# Atividade - Semana 04 - Python (Parte 2)

Esta é atividade semanal sugerida. Você deverá preenchê-la e enviá-la dentro do prazo (até o fechamento da semana corrente).

###Questão 1

Crie uma função que contenha uma estrutura condicional que imprima na tela se um número é positivo ou negativo. Além disso, imprima um aviso de que não é possível testar o valor `0`.
"""

# Questao 1

def verificar_numero(num):
    if num > 0:
        print(f"{num} é positivo.")
    elif num < 0:
        print(f"{num} é negativo.")
    else:
        print("Não é possível testar o valor 0.")

# Testando a função
verificar_numero(5)
verificar_numero(-3)
verificar_numero(0)

"""###Questão 2

Crie uma lista `pessoas` com o nome dos seus familiares preferidos. Imprima o resultado na tela.
"""

# Questao 2

# Lista de familiares preferidos
pessoas = ["Mãe", "Pai", "Irmã", "Avó"]

# Imprimindo a lista
print(pessoas)

"""###Questão 3

Utilizando o método adequado, adicione à lista `pessoas` o nome dos seus amigos preferidos. Além disso, coloque todos os caracteres dessa lista com letra maiúscula. Imprima o resultado na tela.
"""

# Questao 3

# Adicionando amigos à lista
pessoas.extend(["Amigo1", "Amigo2", "Amigo3"])

# Convertendo para maiúsculas
pessoas = [nome.upper() for nome in pessoas]

# Imprimindo a lista atualizada
print(pessoas)

"""###Questão 4

Crie uma função que recebe uma frase e retorna uma lista com cada palavra sendo um elemento dessa lista. Utilize o método adequado. Crie um teste e imprima o resultado na tela.
"""

# Questao 4

def frase_para_lista(frase):
    return frase.split()

# Testando a função
resultado = frase_para_lista("Olá, como você está?")
print(resultado)