# -*- coding: utf-8 -*-
"""Atividade_Semana03_Aline_Melo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_eiiwQXS14Cyd9pzAiT9PMBN38DEoQq

# Atividade - Semana 03 - Python (Parte 1)

Esta é atividade semanal sugerida. Você deverá preenchê-la e enviá-la dentro do prazo (até o fechamento da semana corrente).

###Questão 1

Crie um objeto chamado `nome` e atribua seu nome à ele. Imprima na tela o resultado.
"""

# Questao 1

nome = "Aline Melo"
print(nome)

"""###Questão 2

Imprima na tela qual o tipo (ou classe) do objeto criado no exercício anterior.
"""

# Questao 2

print(type(nome))

"""###Questão 3

Abaixo você encontra uma funcao que calcula o triplo de um valor. Embora, completamente sem documentação. Complete a documentação utilizando comentário iniciados com $\#$.
"""

# Questao 3

#############################
# Documente a funcao abaixo:
#############################

# Esta função recebe um número como parâmetro.
# Ela calcula o triplo desse número multiplicando-o por 3.
# Retorna o resultado do cálculo.

def triplo(numero):
    resultado = 3 * numero
    return resultado

triplo_do_numero = triplo(5)

print('Triplo:', triplo_do_numero)

"""###Questão 4

Crie uma função que calcula o quadrado de um número.

> Ex.: O quadrado de 3 é 3 * 3 = 9 (basta multiplicar o número por ele mesmo)
"""

# Questao 4

def quadrado(numero):

  return numero * numero

resultado = quadrado = quadrado(3)
print(f"O quadrado de 3 é {resultado}.")


# Esta função recebe um número como parâmetro.
# Ela calcula o quadrado desse número multiplicando-o por ele mesmo.
# Retorna o resultado do cálculo.